### ISSUE TITLE
CYBER branch running issues

### ISSUE THREAD

**Issue by ABresting** [aau-network-security/riotpot#23]
Hi,

I tried compiling the code base in CYBER branch and ran into a bunch of errors. Followed the README steps but errors still prevailed. I tried fixing them in my fork:
https://github.com/ABresting/riotpot/tree/CYBER
I can run my fork(CYBER branch), could you please tell me if the existing CYBER branch code works, or should I open a PR to fix that?

**Comment by sastry17** [comment]
Hi @ABresting ,

Please open a PR.
