### ISSUE TITLE
Docker Install problem

### ISSUE THREAD

**Issue by Tonantems** [aau-network-security/riotpot#82]
Hi, when I used docker compose command "docker compose -f docker-compose.yml up -d --build "

failed message show that :

> [+] Building 2.9s (18/19)
>  => [riotpot:development internal] load build definition from Dockerfile   0.0s
>  => => transferring dockerfile: 1.10kB                                     0.0s
>  => [riotpot:development internal] load .dockerignore                      0.0s
>  => => transferring context: 2B                                            0.0s
>  => [deployments-attacker internal] load .dockerignore                     0.0s
>  => => transferring context: 2B                                            0.0s
>  => [deployments-attacker internal] load build definition from Dockerfile  0.0s
>  => => transferring dockerfile: 199B                                       0.0s
>  => [riotpot:development internal] load metadata for docker.io/library/go  1.7s
>  => [deployments-attacker internal] load metadata for docker.io/kalilinux  1.6s
>  => [deployments-attacker 1/3] FROM docker.io/kalilinux/kali-bleeding-edg  0.0s
>  => CACHED [deployments-attacker 2/3] RUN apt-get update &&     apt-get i  0.0s
>  => ERROR [deployments-attacker 3/3] RUN pip install paho-mqtt             1.1s
>  => [riotpot:development 1/9] FROM docker.io/library/golang:1.16@sha256:5  0.0s
>  => [riotpot:development internal] load build context                      0.0s
>  => => transferring context: 6.50kB                                        0.0s
>  => CACHED [riotpot:development 2/9] WORKDIR /go/src/github.com/aau/riotp  0.0s
>  => CACHED [riotpot:development 3/9] COPY go.mod .                         0.0s
>  => CACHED [riotpot:development 4/9] COPY go.sum .                         0.0s
>  => CACHED [riotpot:development 5/9] RUN go mod download                   0.0s
>  => CACHED [riotpot:development 6/9] RUN apt-get update && apt-get instal  0.0s
>  => CACHED [riotpot:development 7/9] COPY . .                              0.0s
>  => CANCELED [riotpot:development 8/9] RUN make riotpot-builder            1.2s
> 
>  [deployments-attacker 3/3] RUN pip install paho-mqtt:
> #0 1.020 error: externally-managed-environment
> #0 1.020
> #0 1.020 × This environment is externally managed
> #0 1.020 ╰─> To install Python packages system-wide, try apt install
> #0 1.020     python3-xyz, where xyz is the package you are trying to
> #0 1.020     install.
> #0 1.020
> #0 1.020     If you wish to install a non-Debian-packaged Python package,
> #0 1.020     create a virtual environment using python3 -m venv path/to/venv.
> #0 1.020     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
> #0 1.020     sure you have python3-full installed.
> #0 1.020
> #0 1.020     If you wish to install a non-Debian packaged Python application,
> #0 1.020     it may be easiest to use pipx install xyz, which will manage a
> #0 1.020     virtual environment for you. Make sure you have pipx installed.
> #0 1.020
> #0 1.020     See /usr/share/doc/python3.11/README.venv for more information.
> #0 1.020
> #0 1.020 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
> #0 1.020 hint: See PEP 668 for the detailed specification.
> 
> failed to solve: process "/bin/sh -c pip install paho-mqtt" did not complete suc        cessfully: exit code: 1

It show failed about paho-mqtt, am I miss some tips ?
OS : Ubuntu 20.04 server
Docker version : 23.0.1 , Docker compose version : v2.16.0

**Comment by RicYaben** [comment]
Hey there! since the GSoC 2023 the repository has been moved to (here)[https://github.com/honeynet/riotpot].
Please use the code in that repository instead and let us know if you still have the same issue! :)
