### ISSUE TITLE
Docker installation issue

### ISSUE THREAD

**Issue by EvilWatermelon** [aau-network-security/riotpot#96]
After `git clone` I want to execute `make up` and it shows an error.

```
docker-compose -p riotpot -f build/docker/docker-compose.yaml up -d --build
/bin/bash: docker-compose: command not found
make: *** [Makefile:16: up] Error 127
```
`docker-compose` is deprecated. `sudo docker compose` should be used now.

**Comment by RicYaben** [comment]
Hey there! 

Thank you for the comment :)
Since the GSoC 2023 the repository has been moved to (here)[https://github.com/honeynet/riotpot].

Can you please open an issue there and send a pull request correcting this issue if this is still true?
